apiVersion: v1
kind: LimitRange
metadata:
  name: test-limits
  namespace: test
spec:
  limits:
  - max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 300m
      memory: 100Mi
    type: Pod
  - default:
      cpu: 300m
      memory: 600Mi
    defaultRequest:
      cpu: 300m
      memory: 200Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 300m
      memory: 3Mi
    type: Container
